app:
  foreign-service:
    account:
      url: http://smava-account-service/v1/account

server:
  servlet:
    context-path: /v1

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger

rest:
  security:
    issuer-uri: http://keycloak-server/auth/realms/master

security:
  oauth2:
    resource:
      id: bank-platform
      token-info-uri: ${rest.security.issuer-uri}/protocol/openid-connect/token/introspect
      user-info-uri: ${rest.security.issuer-uri}/protocol/openid-connect/userinfo
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwn+lqnsNF1hoVZ7WkiMpSsp32c/2s9fDhfqnz30+Jin+AjBYJtYX6qwL1YzRJXgqv2b/86tMAdoTbKbgH2VR4OkyW5vC3MMBYeBNdKkRYQ8L8gy59hkbGdXysLtG/eis/AYodeQKKs6UtVPmko6m+myXOJo3oDd98TAtCrEU79XLV4UCdV81pXuK2lkmrnsieCrS1ydq/eBTSCmgCPd7tLkZHLB1W7naafV9L+iAkOB1aoLe+qd63iRGh1xd3/Orp2gzMhr4TAHXPnqnAsLVqoOIcyTPTPw9tacorT0qoC+x7IXB7qytpy9TyHtQJIXRVdBOAS+P+vmoLaMVZm8F0QIDAQAB-----END PUBLIC KEY-----
